CREATE TABLE IF NOT EXISTS fellowship_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    gender ENUM('Male', 'Female', 'Other') NOT NULL,
    birth_date DATE NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    local_government VARCHAR(255) NOT NULL,
    ward VARCHAR(255) NOT NULL,
    current_address TEXT NOT NULL,
    education_level ENUM('Secondary', 'Diploma', 'Bachelor', 'Masters', 'PhD', 'Other') NOT NULL,
    field_of_study VARCHAR(255) NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    graduation_year YEAR,
    current_occupation VARCHAR(255),
    organization VARCHAR(255),
    previous_volunteer BOOLEAN NOT NULL,
    volunteer_experience TEXT,
    leadership_experience TEXT NOT NULL,
    community_service TEXT NOT NULL,
    why_fellowship TEXT NOT NULL,
    project_idea TEXT NOT NULL,
    expectations TEXT NOT NULL,
    commitment_agreement BOOLEAN NOT NULL,
    reference_name VARCHAR(255) NOT NULL,
    reference_phone VARCHAR(20) NOT NULL,
    reference_relationship VARCHAR(255) NOT NULL,
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
