-- Only include fields present in the new form
CREATE TABLE fellowship_applications (
    id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    state VARCHAR(50) NOT NULL,
    local_government VARCHAR(50) NOT NULL,
    ward VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    residential_address TEXT NOT NULL,
    education_level VARCHAR(50) NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    course_of_study VARCHAR(255) NOT NULL,
    graduation_year INT NULL,
    current_occupation VARCHAR(255) NULL,
    employer_name VARCHAR(255) NULL,
    work_experience TEXT NULL,
    volunteer_experience TEXT NOT NULL,
    skills_competencies TEXT NOT NULL,
    leadership_roles TEXT NOT NULL,
    why_fellowship TEXT NOT NULL,
    challenge_description TEXT NOT NULL,
    fellowship_goals TEXT NOT NULL,
    skills_application TEXT NOT NULL,
    can_accommodate VARCHAR(10) NOT NULL,
    video_path VARCHAR(255) NOT NULL,
    passport_photo_path VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
